name: snowball_stemmer
description: A starting point for Dart libraries or applications.
version: 0.1.0
# homepage: https://github.com/Klabauterman/snowball_stemmer_dart

environment:
  sdk: ">=2.14.3 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
