// Generated by Snowball 2.1.0 - https://snowballstem.org/

import './../base_stemmer.dart';
import './../among.dart';

class english_stemmer extends BaseStemmer {
    late final List<Among> a_0 = [
         Among('arsen', -1, -1),
         Among('commun', -1, -1),
         Among('gener', -1, -1)
    ];

    late final List<Among> a_1 = [
         Among('\'', -1, 1),
         Among('\'s\'', 0, 1),
         Among('\'s', -1, 1)
    ];

    late final List<Among> a_2 = [
         Among('ied', -1, 2),
         Among('s', -1, 3),
         Among('ies', 1, 2),
         Among('sses', 1, 1),
         Among('ss', 1, -1),
         Among('us', 1, -1)
    ];

    late final List<Among> a_3 = [
         Among('', -1, 3),
         Among('bb', 0, 2),
         Among('dd', 0, 2),
         Among('ff', 0, 2),
         Among('gg', 0, 2),
         Among('bl', 0, 1),
         Among('mm', 0, 2),
         Among('nn', 0, 2),
         Among('pp', 0, 2),
         Among('rr', 0, 2),
         Among('at', 0, 1),
         Among('tt', 0, 2),
         Among('iz', 0, 1)
    ];

    late final List<Among> a_4 = [
         Among('ed', -1, 2),
         Among('eed', 0, 1),
         Among('ing', -1, 2),
         Among('edly', -1, 2),
         Among('eedly', 3, 1),
         Among('ingly', -1, 2)
    ];

    late final List<Among> a_5 = [
         Among('anci', -1, 3),
         Among('enci', -1, 2),
         Among('ogi', -1, 13),
         Among('li', -1, 15),
         Among('bli', 3, 12),
         Among('abli', 4, 4),
         Among('alli', 3, 8),
         Among('fulli', 3, 9),
         Among('lessli', 3, 14),
         Among('ousli', 3, 10),
         Among('entli', 3, 5),
         Among('aliti', -1, 8),
         Among('biliti', -1, 12),
         Among('iviti', -1, 11),
         Among('tional', -1, 1),
         Among('ational', 14, 7),
         Among('alism', -1, 8),
         Among('ation', -1, 7),
         Among('ization', 17, 6),
         Among('izer', -1, 6),
         Among('ator', -1, 7),
         Among('iveness', -1, 11),
         Among('fulness', -1, 9),
         Among('ousness', -1, 10)
    ];

    late final List<Among> a_6 = [
         Among('icate', -1, 4),
         Among('ative', -1, 6),
         Among('alize', -1, 3),
         Among('iciti', -1, 4),
         Among('ical', -1, 4),
         Among('tional', -1, 1),
         Among('ational', 5, 2),
         Among('ful', -1, 5),
         Among('ness', -1, 5)
    ];

    late final List<Among> a_7 = [
         Among('ic', -1, 1),
         Among('ance', -1, 1),
         Among('ence', -1, 1),
         Among('able', -1, 1),
         Among('ible', -1, 1),
         Among('ate', -1, 1),
         Among('ive', -1, 1),
         Among('ize', -1, 1),
         Among('iti', -1, 1),
         Among('al', -1, 1),
         Among('ism', -1, 1),
         Among('ion', -1, 2),
         Among('er', -1, 1),
         Among('ous', -1, 1),
         Among('ant', -1, 1),
         Among('ent', -1, 1),
         Among('ment', 15, 1),
         Among('ement', 16, 1)
    ];

    late final List<Among> a_8 = [
         Among('e', -1, 1),
         Among('l', -1, 2)
    ];

    late final List<Among> a_9 = [
         Among('succeed', -1, -1),
         Among('proceed', -1, -1),
         Among('exceed', -1, -1),
         Among('canning', -1, -1),
         Among('inning', -1, -1),
         Among('earring', -1, -1),
         Among('herring', -1, -1),
         Among('outing', -1, -1)
    ];

    late final List<Among> a_10 = [
         Among('andes', -1, -1),
         Among('atlas', -1, -1),
         Among('bias', -1, -1),
         Among('cosmos', -1, -1),
         Among('dying', -1, 3),
         Among('early', -1, 9),
         Among('gently', -1, 7),
         Among('howe', -1, -1),
         Among('idly', -1, 6),
         Among('lying', -1, 4),
         Among('news', -1, -1),
         Among('only', -1, 10),
         Among('singly', -1, 11),
         Among('skies', -1, 2),
         Among('skis', -1, 1),
         Among('sky', -1, -1),
         Among('tying', -1, 5),
         Among('ugly', -1, 8)
    ];

    static final List<int> g_v = [17, 65, 16, 1 ];

    static final List<int> g_v_WXY = [1, 17, 65, 208, 1 ];

    static final List<int> g_valid_LI = [55, 141, 2 ];

    late bool B_Y_found;
    late int I_p2;
    late int I_p1;


    bool r_prelude() {
        B_Y_found = false;
        var v_1 = cursor;
        try {//lab0
            bra = cursor;
            if (!(eq_s('\'')))
            {
                throw BreakLab0();
            }
            ket = cursor;
            slice_del();
        } on BreakLab0 catch(_) {}
        cursor = v_1;
        var v_2 = cursor;
        try {//lab1
            bra = cursor;
            if (!(eq_s('y')))
            {
                throw BreakLab1();
            }
            ket = cursor;
            slice_from('Y');
            B_Y_found = true;
        } on BreakLab1 catch(_) {}
        cursor = v_2;
        var v_3 = cursor;
        try {//lab2
            while(true)
            {
                var v_4 = cursor;
                try {//lab3
                    try { //golab4
                        while(true)                         {
                            var v_5 = cursor;
                            try {//lab5
                                if (!(in_grouping(g_v, 97, 121)))
                                {
                                    throw BreakLab5();
                                }
                                bra = cursor;
                                if (!(eq_s('y')))
                                {
                                    throw BreakLab5();
                                }
                                ket = cursor;
                                cursor = v_5;
                                throw BreakLab4();
                            } on BreakLab5 catch(_) {}
                            cursor = v_5;
                            if (cursor >= limit)
                            {
                                throw BreakLab3();
                            }
                            cursor++;
                        }
                    } on BreakLab4 catch(_) {}
                    slice_from('Y');
                    B_Y_found = true;
                    continue;
                } on BreakLab3 catch(_) {}
                cursor = v_4;
                break;
            }
        } on BreakLab2 catch(_) {}
        cursor = v_3;
        return true;
    }

    bool r_mark_regions() {
        I_p1 = limit;
        I_p2 = limit;
        var v_1 = cursor;
        try {//lab0
            try {//lab1
                var v_2 = cursor;
                try {//lab2
                    if (find_among(a_0) == 0)
                    {
                        throw BreakLab2();
                    }
                    throw BreakLab1();
                } on BreakLab2 catch(_) {}
                cursor = v_2;
                try { //golab3
                    while(true)                     {
                        try {//lab4
                            if (!(in_grouping(g_v, 97, 121)))
                            {
                                throw BreakLab4();
                            }
                            throw BreakLab3();
                        } on BreakLab4 catch(_) {}
                        if (cursor >= limit)
                        {
                            throw BreakLab0();
                        }
                        cursor++;
                    }
                } on BreakLab3 catch(_) {}
                try { //golab5
                    while(true)                     {
                        try {//lab6
                            if (!(out_grouping(g_v, 97, 121)))
                            {
                                throw BreakLab6();
                            }
                            throw BreakLab5();
                        } on BreakLab6 catch(_) {}
                        if (cursor >= limit)
                        {
                            throw BreakLab0();
                        }
                        cursor++;
                    }
                } on BreakLab5 catch(_) {}
            } on BreakLab1 catch(_) {}
            I_p1 = cursor;
            try { //golab7
                while(true)                 {
                    try {//lab8
                        if (!(in_grouping(g_v, 97, 121)))
                        {
                            throw BreakLab8();
                        }
                        throw BreakLab7();
                    } on BreakLab8 catch(_) {}
                    if (cursor >= limit)
                    {
                        throw BreakLab0();
                    }
                    cursor++;
                }
            } on BreakLab7 catch(_) {}
            try { //golab9
                while(true)                 {
                    try {//lab10
                        if (!(out_grouping(g_v, 97, 121)))
                        {
                            throw BreakLab10();
                        }
                        throw BreakLab9();
                    } on BreakLab10 catch(_) {}
                    if (cursor >= limit)
                    {
                        throw BreakLab0();
                    }
                    cursor++;
                }
            } on BreakLab9 catch(_) {}
            I_p2 = cursor;
        } on BreakLab0 catch(_) {}
        cursor = v_1;
        return true;
    }

    bool r_shortv() {
        try {//lab0
            var v_1 = limit - cursor;
            try {//lab1
                if (!(out_grouping_b(g_v_WXY, 89, 121)))
                {
                    throw BreakLab1();
                }
                if (!(in_grouping_b(g_v, 97, 121)))
                {
                    throw BreakLab1();
                }
                if (!(out_grouping_b(g_v, 97, 121)))
                {
                    throw BreakLab1();
                }
                throw BreakLab0();
            } on BreakLab1 catch(_) {}
            cursor = limit - v_1;
            if (!(out_grouping_b(g_v, 97, 121)))
            {
                return false;
            }
            if (!(in_grouping_b(g_v, 97, 121)))
            {
                return false;
            }
            if (cursor > limit_backward)
            {
                return false;
            }
        } on BreakLab0 catch(_) {}
        return true;
    }

    bool r_R1() {
        if (!(I_p1 <= cursor))
        {
            return false;
        }
        return true;
    }

    bool r_R2() {
        if (!(I_p2 <= cursor))
        {
            return false;
        }
        return true;
    }

    bool r_Step_1a() {
        var among_var;
        var v_1 = limit - cursor;
        try {//lab0
            ket = cursor;
            if (find_among_b(a_1) == 0)
            {
                cursor = limit - v_1;
                throw BreakLab0();
            }
            bra = cursor;
            slice_del();
        } on BreakLab0 catch(_) {}
        ket = cursor;
        among_var = find_among_b(a_2);
        if (among_var == 0)
        {
            return false;
        }
        bra = cursor;
        switch (among_var) {
            case 1:
                slice_from('ss');
                break;
            case 2:
                try {//lab1
                    var v_2 = limit - cursor;
                    try {//lab2
                        {
                            var c = cursor - 2;
                            if (c < limit_backward)
                            {
                                throw BreakLab2();
                            }
                            cursor = c;
                        }
                        slice_from('i');
                        throw BreakLab1();
                    } on BreakLab2 catch(_) {}
                    cursor = limit - v_2;
                    slice_from('ie');
                } on BreakLab1 catch(_) {}
                break;
            case 3:
                if (cursor <= limit_backward)
                {
                    return false;
                }
                cursor--;
                try { //golab3
                    while(true)                     {
                        try {//lab4
                            if (!(in_grouping_b(g_v, 97, 121)))
                            {
                                throw BreakLab4();
                            }
                            throw BreakLab3();
                        } on BreakLab4 catch(_) {}
                        if (cursor <= limit_backward)
                        {
                            return false;
                        }
                        cursor--;
                    }
                } on BreakLab3 catch(_) {}
                slice_del();
                break;
        }
        return true;
    }

    bool r_Step_1b() {
        var among_var;
        ket = cursor;
        among_var = find_among_b(a_4);
        if (among_var == 0)
        {
            return false;
        }
        bra = cursor;
        switch (among_var) {
            case 1:
                if (!r_R1())
                {
                    return false;
                }
                slice_from('ee');
                break;
            case 2:
                var v_1 = limit - cursor;
                try { //golab0
                    while(true)                     {
                        try {//lab1
                            if (!(in_grouping_b(g_v, 97, 121)))
                            {
                                throw BreakLab1();
                            }
                            throw BreakLab0();
                        } on BreakLab1 catch(_) {}
                        if (cursor <= limit_backward)
                        {
                            return false;
                        }
                        cursor--;
                    }
                } on BreakLab0 catch(_) {}
                cursor = limit - v_1;
                slice_del();
                var v_3 = limit - cursor;
                among_var = find_among_b(a_3);
                if (among_var == 0)
                {
                    return false;
                }
                cursor = limit - v_3;
                switch (among_var) {
                    case 1:
                        {
                            var c = cursor;
                            insert(cursor, cursor, 'e');
                            cursor = c;
                        }
                        break;
                    case 2:
                        ket = cursor;
                        if (cursor <= limit_backward)
                        {
                            return false;
                        }
                        cursor--;
                        bra = cursor;
                        slice_del();
                        break;
                    case 3:
                        if (cursor != I_p1)
                        {
                            return false;
                        }
                        var v_4 = limit - cursor;
                        if (!r_shortv())
                        {
                            return false;
                        }
                        cursor = limit - v_4;
                        {
                            var c = cursor;
                            insert(cursor, cursor, 'e');
                            cursor = c;
                        }
                        break;
                }
                break;
        }
        return true;
    }

    bool r_Step_1c() {
        ket = cursor;
        try {//lab0
            var v_1 = limit - cursor;
            try {//lab1
                if (!(eq_s_b('y')))
                {
                    throw BreakLab1();
                }
                throw BreakLab0();
            } on BreakLab1 catch(_) {}
            cursor = limit - v_1;
            if (!(eq_s_b('Y')))
            {
                return false;
            }
        } on BreakLab0 catch(_) {}
        bra = cursor;
        if (!(out_grouping_b(g_v, 97, 121)))
        {
            return false;
        }
        try {//lab2
            if (cursor > limit_backward)
            {
                throw BreakLab2();
            }
            return false;
        } on BreakLab2 catch(_) {}
        slice_from('i');
        return true;
    }

    bool r_Step_2() {
        var among_var;
        ket = cursor;
        among_var = find_among_b(a_5);
        if (among_var == 0)
        {
            return false;
        }
        bra = cursor;
        if (!r_R1())
        {
            return false;
        }
        switch (among_var) {
            case 1:
                slice_from('tion');
                break;
            case 2:
                slice_from('ence');
                break;
            case 3:
                slice_from('ance');
                break;
            case 4:
                slice_from('able');
                break;
            case 5:
                slice_from('ent');
                break;
            case 6:
                slice_from('ize');
                break;
            case 7:
                slice_from('ate');
                break;
            case 8:
                slice_from('al');
                break;
            case 9:
                slice_from('ful');
                break;
            case 10:
                slice_from('ous');
                break;
            case 11:
                slice_from('ive');
                break;
            case 12:
                slice_from('ble');
                break;
            case 13:
                if (!(eq_s_b('l')))
                {
                    return false;
                }
                slice_from('og');
                break;
            case 14:
                slice_from('less');
                break;
            case 15:
                if (!(in_grouping_b(g_valid_LI, 99, 116)))
                {
                    return false;
                }
                slice_del();
                break;
        }
        return true;
    }

    bool r_Step_3() {
        var among_var;
        ket = cursor;
        among_var = find_among_b(a_6);
        if (among_var == 0)
        {
            return false;
        }
        bra = cursor;
        if (!r_R1())
        {
            return false;
        }
        switch (among_var) {
            case 1:
                slice_from('tion');
                break;
            case 2:
                slice_from('ate');
                break;
            case 3:
                slice_from('al');
                break;
            case 4:
                slice_from('ic');
                break;
            case 5:
                slice_del();
                break;
            case 6:
                if (!r_R2())
                {
                    return false;
                }
                slice_del();
                break;
        }
        return true;
    }

    bool r_Step_4() {
        var among_var;
        ket = cursor;
        among_var = find_among_b(a_7);
        if (among_var == 0)
        {
            return false;
        }
        bra = cursor;
        if (!r_R2())
        {
            return false;
        }
        switch (among_var) {
            case 1:
                slice_del();
                break;
            case 2:
                try {//lab0
                    var v_1 = limit - cursor;
                    try {//lab1
                        if (!(eq_s_b('s')))
                        {
                            throw BreakLab1();
                        }
                        throw BreakLab0();
                    } on BreakLab1 catch(_) {}
                    cursor = limit - v_1;
                    if (!(eq_s_b('t')))
                    {
                        return false;
                    }
                } on BreakLab0 catch(_) {}
                slice_del();
                break;
        }
        return true;
    }

    bool r_Step_5() {
        var among_var;
        ket = cursor;
        among_var = find_among_b(a_8);
        if (among_var == 0)
        {
            return false;
        }
        bra = cursor;
        switch (among_var) {
            case 1:
                try {//lab0
                    var v_1 = limit - cursor;
                    try {//lab1
                        if (!r_R2())
                        {
                            throw BreakLab1();
                        }
                        throw BreakLab0();
                    } on BreakLab1 catch(_) {}
                    cursor = limit - v_1;
                    if (!r_R1())
                    {
                        return false;
                    }
                    {
                        var v_2 = limit - cursor;
                        try {//lab2
                            if (!r_shortv())
                            {
                                throw BreakLab2();
                            }
                            return false;
                        } on BreakLab2 catch(_) {}
                        cursor = limit - v_2;
                    }
                } on BreakLab0 catch(_) {}
                slice_del();
                break;
            case 2:
                if (!r_R2())
                {
                    return false;
                }
                if (!(eq_s_b('l')))
                {
                    return false;
                }
                slice_del();
                break;
        }
        return true;
    }

    bool r_exception2() {
        ket = cursor;
        if (find_among_b(a_9) == 0)
        {
            return false;
        }
        bra = cursor;
        if (cursor > limit_backward)
        {
            return false;
        }
        return true;
    }

    bool r_exception1() {
        var among_var;
        bra = cursor;
        among_var = find_among(a_10);
        if (among_var == 0)
        {
            return false;
        }
        ket = cursor;
        if (cursor < limit)
        {
            return false;
        }
        switch (among_var) {
            case 1:
                slice_from('ski');
                break;
            case 2:
                slice_from('sky');
                break;
            case 3:
                slice_from('die');
                break;
            case 4:
                slice_from('lie');
                break;
            case 5:
                slice_from('tie');
                break;
            case 6:
                slice_from('idl');
                break;
            case 7:
                slice_from('gentl');
                break;
            case 8:
                slice_from('ugli');
                break;
            case 9:
                slice_from('earli');
                break;
            case 10:
                slice_from('onli');
                break;
            case 11:
                slice_from('singl');
                break;
        }
        return true;
    }

    bool r_postlude() {
        if (!(B_Y_found))
        {
            return false;
        }
        while(true)
        {
            var v_1 = cursor;
            try {//lab0
                try { //golab1
                    while(true)                     {
                        var v_2 = cursor;
                        try {//lab2
                            bra = cursor;
                            if (!(eq_s('Y')))
                            {
                                throw BreakLab2();
                            }
                            ket = cursor;
                            cursor = v_2;
                            throw BreakLab1();
                        } on BreakLab2 catch(_) {}
                        cursor = v_2;
                        if (cursor >= limit)
                        {
                            throw BreakLab0();
                        }
                        cursor++;
                    }
                } on BreakLab1 catch(_) {}
                slice_from('y');
                continue;
            } on BreakLab0 catch(_) {}
            cursor = v_1;
            break;
        }
        return true;
    }

    bool stem() {
        try {//lab0
            var v_1 = cursor;
            try {//lab1
                if (!r_exception1())
                {
                    throw BreakLab1();
                }
                throw BreakLab0();
            } on BreakLab1 catch(_) {}
            cursor = v_1;
            try {//lab2
                {
                    var v_2 = cursor;
                    try {//lab3
                        {
                            var c = cursor + 3;
                            if (c > limit)
                            {
                                throw BreakLab3();
                            }
                            cursor = c;
                        }
                        throw BreakLab2();
                    } on BreakLab3 catch(_) {}
                    cursor = v_2;
                }
                throw BreakLab0();
            } on BreakLab2 catch(_) {}
            cursor = v_1;
            r_prelude();
            r_mark_regions();
            limit_backward = cursor;
            cursor = limit;
            var v_5 = limit - cursor;
            r_Step_1a();
            cursor = limit - v_5;
            try {//lab4
                var v_6 = limit - cursor;
                try {//lab5
                    if (!r_exception2())
                    {
                        throw BreakLab5();
                    }
                    throw BreakLab4();
                } on BreakLab5 catch(_) {}
                cursor = limit - v_6;
                var v_7 = limit - cursor;
                r_Step_1b();
                cursor = limit - v_7;
                var v_8 = limit - cursor;
                r_Step_1c();
                cursor = limit - v_8;
                var v_9 = limit - cursor;
                r_Step_2();
                cursor = limit - v_9;
                var v_10 = limit - cursor;
                r_Step_3();
                cursor = limit - v_10;
                var v_11 = limit - cursor;
                r_Step_4();
                cursor = limit - v_11;
                var v_12 = limit - cursor;
                r_Step_5();
                cursor = limit - v_12;
            } on BreakLab4 catch(_) {}
            cursor = limit_backward;
            var v_13 = cursor;
            r_postlude();
            cursor = v_13;
        } on BreakLab0 catch(_) {}
        return true;
    }
}

class BreakLab0{}
class BreakLab1{}
class BreakLab2{}
class BreakLab3{}
class BreakLab4{}
class BreakLab5{}
class BreakLab6{}
class BreakLab7{}
class BreakLab8{}
class BreakLab9{}
class BreakLab10{}
